
/**
 * The Card class stores the suit and rank of each card along with their descriptions that are displayed to the user
 * @version 1.1
 * @author jbehrend4, dziege1
 */
public class Card {
    private int suit;
    private int number;
    private String discriptSuit;
    private String discriptNumber;
    private GenerateCard cardGen = new GenerateCard();

        /**
        * Returns the numeric value of the generated suit
        * @return A number between 1 and 4 which represents the suit of the card
        */
    public int getSuit() {
        return suit;
    }
    /**
        *Sets the numeric value for the suit that is generated by the GenerateCard class
        */
    public void setSuit() {
        this.suit = cardGen.generateSuit();
    }
    /**
        * Returns the numeric value of the card's generated rank
        * @return A number between 2 and 14 which represents the rank of the card
        */
    public int getNumber() {
        return number;
    }
    /**
        * Sets the numeric value for the rank that is generated by the GenerateCard class
       */
    public void setNumber() {
        this.number = cardGen.generateNumber();
    }
    /**
        *  Returns the value that is generated by setDescriptSuit()
        * @return A String that contains which suit the card is so the user knows what their card is
        */
    public String getDiscriptSuit() {
        return discriptSuit;
    }

        /**
        * Sets the descriptSuit String to the name of the suit that was generated by the GenerateCard class
        */    
    public void setDiscriptSuit() {
        switch(suit){
            case 1:
                this.discriptSuit = "Clubs";
                break;
            case 2:
                this.discriptSuit = "Diamonds";
                break;
            case 3:
                this.discriptSuit = "Hearts";
                break;
            case 4:
                this.discriptSuit = "Spades";
                break;
            default:
                this.discriptSuit = "None";
                break;
        }
    }
    /**
        * Returns the value that is generated by setDescriptNumber()
        * @return  A String that contains the rank of the card so the user knows what their card is
        */
    public String getDiscriptNumber() {
        return discriptNumber;
    }
    /**
        * Sets the descriptNumber String to equal either the number or name for the rank that was generated
        * by the GenerateCard class
        */
    public void setDiscriptNumber() {
        switch(number){
            case 1:
                this.discriptNumber = "Ace";
                break;
            case 2:
                this.discriptNumber = "2";
                break;
            case 3:
                this.discriptNumber = "3";
                break;
            case 4:
                this.discriptNumber = "4";
                break;
            case 5:
                this.discriptNumber = "5";
                break;
            case 6:
                this.discriptNumber = "6";
                break;
            case 7:
                this.discriptNumber = "7";
                break;
            case 8:
                this.discriptNumber = "8";
                break;
            case 9:
                this.discriptNumber = "9";
                break;
            case 10:
                this.discriptNumber = "10";
                break;
            case 11:
                this.discriptNumber = "Jack";
                break;
            case 12:
                this.discriptNumber = "Queen";
                break;
            case 13:
                this.discriptNumber = "King";
                break;
            default:
                this.discriptNumber = "None";
                break;
        }
    }
    
    
        
}
